# Generated by Django 2.2.4 on 2024-04-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240420_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image6',
        ),
    ]
