# Generated by Django 2.2.4 on 2024-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240420_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
