# Generated by Django 2.2.4 on 2024-04-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240422_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description_long',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='item',
            name='hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'sale'), ('N', 'new'), ('P', 'promotion')], max_length=1),
        ),
    ]
