# Generated by Django 2.2.4 on 2024-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240601_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
