# Generated by Django 2.2.4 on 2024-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='Miami', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='Florida', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='freight_estimate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='local_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
