# Generated by Django 2.2.4 on 2025-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240714_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keywords', models.TextField()),
                ('is_indexable', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='')),
                ('content', models.TextField(default=None)),
                ('additional_css', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='is_indexable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'sale'), ('N', 'new'), ('P', 'promotion'), ('U', 'sold')], max_length=1),
        ),
    ]
