# Generated by Django 2.2.4 on 2025-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_item_youtube_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sorting_position',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
