# Generated by Django 2.2.4 on 2024-05-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240423_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='engine',
            field=models.CharField(default='Isuzu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='make',
            field=models.CharField(default='Multiquip', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(default='DCA45USI', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
    ]
