# Generated by Django 2.2.4 on 2024-05-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
