# Generated by Django 2.2.4 on 2024-07-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_billingaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
