# Generated by Django 2.2.4 on 2025-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20250122_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='includes_floating_contact_icons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='includes_icon_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='script_files',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='style_files',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
