# Generated by Django 2.2.4 on 2025-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250224_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='youtube_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
